export const env = {
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID!,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET!,
  NEXTAUTH_SECRET: process.env.NEXTAUTH_SECRET!,
  GUEST_RECOVERY_KEY_SECRET: process.env.GUEST_RECOVERY_KEY_SECRET,
};
