import type { Metadata } from "next";
import "../../styles/globals.css";
import Providers from "../providers";
import { Header } from "@/components/Header";
import { MeProvider } from "@/context/MeContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-zinc-950 text-slate-900 min-h-screen">
        <Providers>
          <MeProvider>
            <Header />
            {children}
          </MeProvider>
        </Providers>
      </body>
    </html>
  );
}
